version: '3'
services:

  # datadog:
  #   build: datadog
  #   pid: host
  #   environment:
  #    - DD_API_KEY=${DD_API_KEY}
  #    - DD_SITE=datadoghq.com
  #    - DD_LOGS_ENABLED=true
  #   volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /proc/:/host/proc/:ro
  #    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  #    - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #   networks:
  #     - quarkus
  #   depends_on:
  #     - postgres
  #     - documents

  documents:
    build: ./apps/documents
    environment:
      POSTGRES_USER: postgres
      QUARKUS_DATASOURCE_DB-KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: p4ssw0rd
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/postgres"
      QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION: drop-and-create
    ports:
      - "8080:8080"
    networks:
      - quarkus
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - quarkus
  
networks:
  quarkus:
    driver: bridge

volumes:
  postgres:
